DROP TABLE usuario;
CREATE TABLE usuario (
	id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	correo VARCHAR(50),
	clave VARCHAR(20),
	fechaNacimiento DATE,
	PRIMARY KEY(id)
);